gross_income=input("enter the gross income of the person ")
dependent=input("enter the number of dependent pupil ") 
gi=float(gross_income)
depend=int(dependent)
taxable_income=float(gi-10000-(3000*depend))
tax=float(taxable_income)*(20/100)
print("taxable income ")
print(taxable_income)
print("tax")
print(tax)